env:
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  'prettier/prettier': error
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
